### PR TITLE
PyqtgraphViewer

### PR DESCRIPTION
**Pull request by prybalko**
Image viewer based on Pyqtgraph lib

### CODE REVIEW

**Comment by pavel-rybalko** [comment]
I've added a gevent support for the viewer, but it's kinda dirty and requires press "Enter" after entering a command

**Comment by pavel-rybalko** [comment]
I've done some tests and measurements regarding performance of `Pyqtgraph` library.
I wrote a [script](https://gist.github.com/pavel-rybalko/27b0b5ceeac34cb682f8), which creates a viewer and updates it in another thread / process as fast as it can. The results of performance are presented in the following table (clickable).
selection_052
As you can see, the results are not really impressive and comparable with Matplatlib. 

However, I found another library for visualization , which is OpenGL-based library called [Vispy](https://github.com/vispy/vispy). And it works pretty fast ([here](https://gist.github.com/pavel-rybalko/3805d82630993d3c077c) is my script):
selection_051
But this library is still under development and has some crucial problems with memory leakage ([issue 1](https://github.com/vispy/vispy/issues/724), [issue 2](https://github.com/vispy/vispy/issues/735))

**Comment by tfarago** [comment]
Nice summary, thanks. I would *not* go for Pyqtgraph and wait for vispy.

**Comment by pavel-rybalko** [comment]
ToDo:
latency test vs Matplotlib

**Comment by campagnola** [comment]
Sorry to interrupt; I got here by way of a related discussion on vispy. Your pyqtgraph test uses ImageView, which is not intended for video performance (the histogram computation and plotting is quite expensive). I recommend looking at `examples/VideoSpeedTest.py` for examples of the kind of framerates you can expect.

**Comment by matze** [comment]
Thanks for the pointer. I hope @pavel-rybalko could redo the test before leaving back?

**Comment by pavel-rybalko** [comment]
Here is an updated graph:
selection_012
I didn't write my own script for testing, just trustfully used `examples/VideoSpeedTest.py`

Note: I limited FPS axis an the graph by 100

**Comment by campagnola** [comment]
That looks about right. Also note that the vispy framerates are probably limited by the GUI toolkit; their theoretical maxima should be much higher (so you will need much less CPU time to achieve the same framerate on vispy than other libraries).

**Comment by pavel-rybalko** [comment]
I wrote a [script](https://gist.github.com/pavel-rybalko/27b0b5ceeac34cb682f8), which uses `GraphicsView`  and update images in another process. It works fine, but we need to integrate it into `RemoteGraphicsView` (which implements multithreading) or to implement it like in my script (explicit multiprocessing). But already I don't have time for that though.

**Pull request closed without merging**
