### PR TITLE
[WIP] Print exceptions of async calls

### PR DESCRIPTION
**Pull request by MarcusZuber**
A callback will print exceptions of async functions.
This can be enabled and disabled via concert.config.ENABLE_PRINT_ASYNC_EXCEPTION.

### CODE REVIEW

**Comment by MarcusZuber** [comment]
Yes. I realized it a few seconds after the commit. I have to work on somethin else now, but I will proceed with it in the near future.

**Comment by matze** [comment]
If you could come up with a tiny test, I'd say it's ready for a merge. What about you @tfarago?

**Comment by MarcusZuber** [comment]
I want to include the implementation for gevents as well. For now it works only with concurrent.futures.

**Comment by tfarago** [comment]
Let's wait for the gevent, the tests and maybe a line in the docs and we're good to go.

**Comment by MarcusZuber** [comment]
Beside that a new input line after the printing would be nice it works for futures and gevent-futures.
But I have no idea to write a test to check if the printing happend.

**Comment by tfarago** [comment]
I think after asyncio this will be obsolete, if not, re-open.

**Pull request closed without merging**
