### PR TITLE
Split producer in frame_producer and abort_handler

### PR DESCRIPTION
**Pull request by MarcusZuber**
I didn't test it so far, just to show you the idea of it.

### CODE REVIEW

**Comment by MarcusZuber** [comment]
In the abort_handler the user can disable everything, that maybe is still ruining from the producer.

**Comment by tfarago** [comment]
This change seems weird to me, I as a generator produce something and if something goes wrong I tell the acquisition to come back to me for clean up. Why would I go through acquisition?

I personally would write my producer in such a way that it has no side effects, i.e. I would use try-finally inside it. (This has to be properly documented so that everyone who works with this knows they have to do it like this, which is currently not the case unfortunately...) I think that's your motivation behind it, right? But let's just not forget that there _must_ be some responsibility also left on the programmers who write the executive code.

**Comment by tfarago** [comment]
for example:

```python
def produce():
    try:
        for i in range(10):
            yield camera.grab()
    finally:
        self.stop_motors().join()

acq = Acquisition('radios', produce)
```

**Comment by tfarago** [comment]
Pin this, possibly re-visit after python 3 transition and native asyncio support.

**Pull request closed without merging**
