### PR TITLE
Add device names

### PR DESCRIPTION
**Pull request by tfarago**
which is convenient for logging.

### CODE REVIEW

**Comment by tfarago** [comment]
Using Tango names and so on is trivial.

**Comment by MarcusZuber** [comment]
Is it possible to get the name of the instance and put it as the name in the class? `ddoc()` also somehow figures out the names in the global scope.

**Comment by tfarago** [comment]
> What do you think of moving this to `Parameterizable`? Then also experiments would have names.

That's a very abstract thing, I wouldn't put it there

**Comment by tfarago** [comment]
> Is it possible to get the name of the instance and put it as the name in the class? `ddoc()` also somehow figures out the names in the global scope.

Unfortunately it doesn't work for devices instantiated in the session. Apart from that, it's super-magicky and very slow. Just asking for the stack takes 3.5 ms on my machine.

I will play with it anyway and we can decide later.

**Comment by tfarago** [comment]
19ff89c966401d23ddccbcdd9a7e3c1c96b35a42 adds what you asked for.

**Comment by tfarago** [comment]
@MarcusZuber 13ae24a  implements the magicky name resolution in a more efficient way, it looks up the name only once and then caches thanks to `memoize`. I can live with this for now, at least we could test it. IMO convenience wins over magic.

**Comment by tfarago** [comment]
So I'd remove all the commits before.

**Comment by MarcusZuber** [comment]
When the device is declared in the session it works:
`[2020-05-07 11:59:07,577] INFO: concert.base: test: set Camera::dimax.frame_rate='100.0 / second'
`
When created within the running session this is the result:

`[2020-05-07 12:00:12,720] INFO: concert.base: test: set Camera::self.frame_rate='5.0 / second'
`

I think this is fine so far.

**Comment by tfarago** [comment]
Alright, now it tries to be even more clever. Please check again and if there are no complaints, I will update the documentation and merge.

**Comment by MarcusZuber** [comment]
I would like to try it under real conditions on monday again. I saw a strange interference with our local sessions, that I don't understand so far.

**Comment by tfarago** [comment]
Alright, we wait. Can you describe the interference in the meantime? Maybe I can figure something out even before Monday.

**Comment by MarcusZuber** [comment]
Now it works...
Maybe I was just too tired yesterday.

The only thing I just found out. In the log the name is written, however the name-property of the device is not automatically set. What is the difference between `Device.name` and `Property.name_for_log` ?

**Comment by tfarago** [comment]
There is no name property, I will discard the old commits.

**Comment by tfarago** [comment]
Alright, let's give this a try.

**Pull request merged**
