### PR TITLE
Monochromator implementation with the possibility to scan

### PR DESCRIPTION
**Pull request by MarcusZuber**
Todo:
- [x] add tests
- [x] Test viewer (= check https://github.com/ufo-kit/concert/issues/407)

### CODE REVIEW

**Comment by MarcusZuber** [comment]
Open for discussions

**Comment by tfarago** [comment]
What do you want to tube? :smiley:

**Comment by tfarago** [comment]
I don't think it's best idea to put all the showing and stuff to the class. I'd put that elsewhere.

**Comment by MarcusZuber** [comment]
> I don't think it's best idea to put all the showing and stuff to the class. I'd put that elsewhere.

My idea was to provide a way to do this without kowing about ploting the series etc...

**Comment by tfarago** [comment]
> > I don't think it's best idea to put all the showing and stuff to the class. I'd put that elsewhere.
> 
> My idea was to provide a way to do this without kowing about ploting the series etc...

That you can still do for the user, just not in the class because it doesn't belong there IMHO. Why can't we have `concert.processes.[beamline,common].scan_bragg_angle`?

**Comment by MarcusZuber** [comment]
> > > I don't think it's best idea to put all the showing and stuff to the class. I'd put that elsewhere.
> > 
> > 
> > My idea was to provide a way to do this without kowing about ploting the series etc...
> 
> That you can still do for the user, just not in the class because it doesn't belong there IMHO. Why can't we have `concert.processes.[beamline,common].scan_bragg_angle`?

But this will be basically ascan(motor[pos], diode.get_intensity()) ...

**Comment by tfarago** [comment]
You can make a very high-level user convenience function which even plots and does everything. Exactly like you wrote it, just take it out of the class because the scan is actually a higher level functionality which uses the monochromator. I'd like to make the scan "atomic" later, i.e. make sure the shutter is opened and closed and so on. This function can then easily blow up.

**Comment by MarcusZuber** [comment]
Now plot_callback can be plt.show with plt an instance of PyplotViewer.

Question @tfarago, @EliasHamann, @angelicacecilia: What should happen if no plot_consumer is provided? Should I open a new one or should the plotting be ommited?

**Comment by MarcusZuber** [comment]
Maybe, it is nicer to pass the viewer instead of the viewer.show?

**Comment by EliasHamann** [comment]
open for discussion: should we make kind of ascan_brag_angle and dscan_bragg_angle, since the implementation right now always assumes you are already in the center and do the scan from -range/2 to +range/2... (would correspond to dscan_bragg_angle). if you are far off or want to scan arbitrary ranges a functionality with ascan would maybe be nice. (in principle would be ciopy and paste of the existing code just with different start and end points of the scan)...
What do you think?

**Comment by MarcusZuber** [comment]
My ascan is basically a dscan...

What about the possibility to pass a center position? If it is not provided we scan around the current position.

**Comment by EliasHamann** [comment]
this would be possible, however this would not allow asymmetric scans with different ranges on both flanks of the peak; but I don't know if this will be needed. 
maybe we could ask the opinion of the others too...

**Comment by angelicacecilia** [comment]
I find all the solutions very suitable to what we need.
In practice we will never be on the peak of the rocking curve when we put the monochromator in. We will rather be somewhere around and we will need 2-3 scans to get a symmetric scan. In SPEC I usually use the dscan for the first scans, to find the region of interest. For the fine scan I use the ascan and I move the motors absolutely. But as I said at the beginning of my message, I am favourable to whatever working solution make everybody happy.

**Comment by MarcusZuber** [comment]
Now you only provide the `PyplotViewer `instance and you have a `center_point` parameter, where you can specify the center of the scan. If the `center_point` is `None `the current bragg angle is used for the scan.

I will add also the test now.

**Comment by MarcusZuber** [comment]
What about the `show_tune_scan` function? Should it stay there for simple usage of the monochromator or is the user skilled enough to do a plot?

**Comment by MarcusZuber** [comment]
From my side we could merge.

**Comment by MarcusZuber** [comment]
How about to change the `show_tune_scan(self)` to `get_last_tune_scan` that returns just the values?
The the user would just do `plt.show(mono.get_last_tune_scan())` and we don't have the plotting stuff in the monochromator class.

**Pull request merged**
