### PR TITLE
Added LensChanger

### PR DESCRIPTION
**Pull request by MarcusZuber**
@tfarago Besides the name, I like it like it is right now. If you come up with something more creative, I'm open to it.

### CODE REVIEW

**Comment by tfarago** [comment]
Please fix the flake8 errors, other than that :+1:

**Comment by MarcusZuber** [comment]
Done. Since when am I no longer allowed to use tabs for indentation in pep8?

**Comment by tfarago** [comment]
I think you could never have.

**Comment by MarcusZuber** [comment]
> pep8

pep8 concert/devices/lenschangers/*
concert/devices/lenschangers/base.py:2:80: E501 line too long (86 > 79 characters)

I don't get pep8 errors.

**Comment by tfarago** [comment]
Ups, sorry, I meant flake8.

**Comment by MarcusZuber** [comment]
I also don't get any flake8 errors...

**Comment by tfarago** [comment]
Sorry, my bad, forgot to pull...

**Pull request merged**
