### PR TITLE
experiments: add per-run log handler

### LINKED ISSUE #438: Seperate log files for single experiment executions
I often put something like this in the `Experiment.prepare` to get a logger in the Experiment class, that creates one (additional) log-file for each experiment run in the folder of the current walker position, that has only the experiment related infos.

```
def prepare(self):
	self.logger = logging.getLogger("CTScan")
	handler = logging.FileHandler(self.walker.current + "/CTScan.log")
	self.logger.handlers = []

	formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
	handler.setFormatter(formatter)
	handler.setLevel(logging.INFO)
	self.logger.addHandler(handler)

	self.logger.info("Exposure time %s" % self._camera.exposure_time)
```

I could add this directly in the base Experiment class, if nobody sees a drawback by doing this.

### PR DESCRIPTION
**Pull request by tfarago**
fixes #438

### CODE REVIEW

**Comment by MarcusZuber** [comment]
Ha, almost the same as I just did ;-)

**Comment by MarcusZuber** [comment]
The only difference it the llog-level. What do you think? Do we want to have the global log level, or an experiment specific?
I would prefer a experiment specific one, so I don't get all the spam of the motor setter etc. when I test a new Experiment.

**Comment by MarcusZuber** [comment]
You should also chane the LOG in the experiment to self.log

**Comment by tfarago** [comment]
> Ha, almost the same as I just did ;-)

Did we really push this at the same time after those weeks of nothingness??

**Comment by MarcusZuber** [comment]
> > Ha, almost the same as I just did ;-)
> 
> Did we really push this at the same time after those weeks of nothingness??

I waited until the other experiment stuff was finished.

**Comment by tfarago** [comment]
> The only difference it the log-level. What do you think? Do we want to have the global log level, or an experiment specific?

We can add that.

> I would prefer a experiment specific one, so I don't get all the spam of the motor setter etc. when I test a new Experiment.

There is no clutter thanks to the logging hierarchy.

**Comment by MarcusZuber** [comment]
Ah, one more thing. We could automatically print all Parameters in the log file in the `run()`. To make it a little bit more "idiot proof".

**Comment by MarcusZuber** [comment]
Just with 
`self.log.info(self)`

**Comment by tfarago** [comment]
Done and done, please check.

**Comment by tfarago** [comment]
I like LOG because it's consistent. what users do in their own code is their business.

**Pull request merged**
