### PR TITLE
coroutines: Fix queue's occasional hanging

### PR DESCRIPTION
**Pull request by tfarago**
If the generator exited after the last item in the queue had been processed it
might have blocked forever waiting for a new item to come.

### CODE REVIEW

**Comment by matze** [comment]
I merged a quick fix but this PR should still merge cleanly.

**Comment by tfarago** [comment]
@MarcusZuber this could be interesting for you.

**Comment by MarcusZuber** [comment]
I'm looking forward to it. But I still don't get why the old implementation did not work in all cases.

**Comment by tfarago** [comment]
I boiled it down to this:
```python
def make_images():
    for im in images:
        yield im
    time.sleep(1)


def write_async(process_all=True, block=True):
    coro = walker.write()
    coro = queue(coro, process_all=process_all, block=block)

    inject(make_images(), coro)
```

For some reason, the `GeneratorExit` exception is emitted only *after* the `time.sleep(1)`, i.e. that the consumer thread in the `queue` coroutine gets ahead and waits for another item by the `queue.get()` which never comes.

**Comment by tfarago** [comment]
It actually makes sense, because the whole *function* is a generator, hence, it exists when the function exits and not just the for loop.

**Comment by tfarago** [comment]
This has been solved elsewhere 1b471108aac37051f16b0f939cf6b78a8e4338c2

**Pull request closed without merging**
