### PR TITLE
Implementation of velocity calculation for continuous motors

### PR DESCRIPTION
**Pull request by MarcusZuber**
The _get_velocity command now calculates the velocity by measuring the
motor position twice and calculates the current velocity out of these
values since many motors do not feature a measured velocity.

Open for discussion of a better solution!

### CODE REVIEW

**Comment by tfarago** [comment]
I like it. We should reflect the changes in the dummy motors, however. They could use the `time` module to compute their position based on velocity and then the `_get_velocity` implementation can be dropped completely from the dummy motors. I will write the tests when that's done.

**Comment by MarcusZuber** [comment]
It seams to work. I'm open for comments!
Should the LinearMotor and RotationMotor also get a readable (calculated) velocity or only the Continuous ones?

**Comment by tfarago** [comment]
I think we should keep the simple motors really simple if there is no real need to stuff them with functionality, so no. They can even return 0 as far as I am concerned.

**Comment by MarcusZuber** [comment]
Just found out, that one thing is still missing. The velocity can not be set in the dummy motors. I will include it in the next days.

**Comment by MarcusZuber** [comment]
@tfarago If you could help me setting up the test properly we could finish this.

**Comment by tfarago** [comment]
I would first deal with #435, then adjust code here accordingly and proceed. In general it's fine.

**Comment by tfarago** [comment]
@MarcusZuber have you reviewed this since #435 was merged?

**Comment by MarcusZuber** [comment]
Not yet. But basically one must change the limits from +- inf to None. The rest should be fine.

**Comment by MarcusZuber** [comment]
Ok, it seams to be a bit broken. I will rebase it and fix it.

**Comment by MarcusZuber** [comment]
OK, now it should work out. The only failing tests are already in the master branch :flushed: failing.

**Comment by tfarago** [comment]
OK, the failing tests have nothing to do with this PR, merging.

**Pull request merged**
