### PR TITLE
Refactor align_rotation_axis

### PR DESCRIPTION
**Pull request by tfarago**

### CODE REVIEW

**Comment by MarcusZuber** [comment]
Does this also work with a sphere instead of a needle tip (typically used for laminography)?

Could you also return the measured angles, that are not optimized?
E.g. in the laminography case I only want to optimize the roll, but it would be nice to get the measured pitch angle for the reconstruction.

**Comment by tfarago** [comment]
> Does this also work with a sphere instead of a needle tip (typically used for laminography)?

Do you have data I could test it on?


> 
> Could you also return the measured angles, that are not optimized?
> E.g. in the laminography case I only want to optimize the roll, but it would be nice to get the measured pitch angle for the reconstruction.

Sure, will do.

**Comment by MarcusZuber** [comment]
> > Does this also work with a sphere instead of a needle tip (typically used for laminography)?
> 
> Do you have data I could test it on?

Mathias will send you some data.

**Comment by tfarago** [comment]
Finished. Now you can check the angles by the future result or like this:
```python
images = acquire_frames_360(camera, rot_motor, 10).result()
tips = find_needle_tips(images)
# ot
tips = find_sphere_centers(images)
rotation_axis(tips)
```

**Comment by tfarago** [comment]
For future me: tested with the needle, the new very sharp needle and Ni spheres from @MathiasHurst

**Comment by tfarago** [comment]
@MarcusZuber you used this at the beam line, right? Can we merge?

**Comment by MarcusZuber** [comment]
We used it with the needles, but I think you wanted to make it also to work with the spheres.

**Pull request merged**
