### PR TITLE
Enable locking and unlocking walkers

### PR DESCRIPTION
**Pull request by tfarago**
And copy walkers in acquisitions consumers.

### CODE REVIEW

**Comment by MarcusZuber** [comment]
How about putting the copy etc. in the `inside` context manager?

You could use it then like:
```
with walker.inside(dataset) as local_walker:
   local_walker.write ....
```

**Comment by MarcusZuber** [comment]
And the inside like

```
@contextmamager
def inside(self, name):
    local_writer = copy(self)
    local_writer.descend(name)
    return(local_writer)
```

**Comment by tfarago** [comment]
No no, I did that in a hurry and there must be a better way. And also if a method creates another instance of the class, that raises a red flag to me.

**Comment by MarcusZuber** [comment]
I don't see the problem to copy a class, that does not hold any data and should be deleted when the `inside` is exited.
Otherwise, we have to tell the user, that he needs to make a copy any time he uses the walker....

**Comment by MarcusZuber** [comment]
To prevent that the user makes to many copies that don't get deleted:
```
@contextmamager
def inside(self, name):
    local_writer = copy(self)
    local_writer.descend(name)
    try:
        yield local_writer
    finally:
        del local_writer
```

And the root could be changed in the copy, so you can not break out of the inside-direcrory.

**Review by MarcusZuber — COMMENTED** [review]
There is one "use-case", where the logging-setup can cause an exception: When the file system is full.

**Comment by tfarago** [comment]
> There is one "use-case", where the logging-setup can cause an exception: When the file system is full.

OK, but then the experiment _should_ raise an exception before it even starts, that's OK.

**Comment by tfarago** [comment]
Alright, now it should be much better.

**Comment by tfarago** [comment]
@sgasilov, please check if this could break your concert scripts and GUI, I think not, but still.

**Comment by MarcusZuber** [comment]
But now you lock the writer inside of the `inside`. This means a second `inside `call will create an exception.

**Comment by tfarago** [comment]
No, why? The second `inside` will wait until the lock is released and then do its thing.

**Comment by MarcusZuber** [comment]
Will it release the lock? But also when it blocks until the first is done I don't like it so much. E.g. I have the ImageWriter addon and an Addon that writes flat-corrected frames, that both (should) use an `inside`. Then one of them will be blocked for the whole Acquisition.

**Comment by MarcusZuber** [comment]
Ok. The `inside` is only active for creating the write and then leaves the context.

What still bothers me a bit is, that if you directly use the `inside` on multiple locations, the lock will block the code (when the user does not understand that he is only allowed to use it to get the writer inside the `inside`). 

What do you think about changing the `inside` to private and making a `create_writer_inside` function?

**Comment by tfarago** [comment]
Alright, this is how I had it originally but thought needing two "withs" in addons was weird, but actually why not like this, it's also well-aligned with the `async with device` mechanism.

**Comment by MarcusZuber** [comment]
I would propose to move the `wrapper_writer` to the `walker` (with the name as argument).
I use the walker.writer also without the addons and this would make it easier to handle.

The rest I like it now!
Tomorrow morning I will test it and check if I find a way to break it :smirk:.

**Comment by tfarago** [comment]
That's taking it too far. If the lock is acquired in some internal method and the user wants to use it as well it will cause a deadlock:
```python
async with walker:
    walker.wrapped_writer(...) # deadlock
```
This stuff is for "expert" users for very fine control so I think the responsibility should stay on the programmer side (explicit is better than implicit), i.e. they need to think about what they are doing.
We could remove the second context manager by having `create_writer` use the the `inside` if you like.

**Comment by MarcusZuber** [comment]
> We could remove the second context manager by having `create_writer` use the the `inside` if you like.

This I like. The `create_writer` would not lock the `walker` but would always give me a writer in a subfolder. Then the user can call as many `walker.create_writer` as he likes.
In the "normal" experiment the `experiment.run()` would do the `descend`/`ascend` and in the addons the `create_writer` would be used (which does not move the `walker.current` away from the experiment base folder).

Do we really need to make the `walker.inside` public then? For almost all cases the `create_writer` could be used and the rest could be done with the lock and ascend/descend.

**Comment by MarcusZuber** [comment]
Almost.
When you create multiple writers "at the same time" you still have the issue with the messed up directories. I had the idea, that the `create_writer` would not change the `walker.current`. But this requires many changes.

What do you think?

PS: It's a pity that asyncio does not feature reentrant locks. Then it would be easy. Here https://github.com/python/asyncio/issues/439 they decided, that nobody needs this...

**Comment by tfarago** [comment]
> What still bothers me a bit is, that if you directly use the inside on multiple locations, the lock will block the code (when the user does not understand that he is only allowed to use it to get the writer inside the inside).

Now we are starting to spin in circles. If I revert it to how it was before we will get to the cited point above again. I want to keep it like it is now becuase
- it's aligned with the rest of the locking code
- user has full control
- this is advanced stuff, hence users must know what they are doing and for that they need the previous point

**Review by MarcusZuber — APPROVED** [review]
I like it.

When I was looking at the code: Why is there `return self` in the ascend/descend? And when there is a reason, why does `home()` not return the walker-instance?

**Comment by tfarago** [comment]
Becuse you can do `walker.descend('foo').descend('bar'); walker.ascend().ascend()`. There is no point for this in `home`.

**Pull request merged**
