### PR TITLE
Fix FlatCorrectedBackproject

### PR DESCRIPTION
**Pull request by tfarago**
Now the backprojector works, I will make a simple session now to check consistency of results.

### CODE REVIEW

**Comment by tfarago** [comment]
Deals with #380

**Comment by matze** [comment]
If the test passes – which I don't doubt – you can merge :+1:

**Comment by tfarago** [comment]
Wait wait, let's wait for the other part which is inconsistency.

**Comment by tfarago** [comment]
On the camlin machine you have a `check-fcbp` session and you can do both runs fc and nofc and see the results are wrong. I guess there is something wrong with the 1D array passing to the framework, can you check that please?

**Comment by matze** [comment]
The flat correction works as expected, i.e. the resulting sinogram has much less vertical artifacts and appears more even. Trying now to guess what happens passing on to the reconstruction.

**Comment by tfarago** [comment]
Hmm, that would have been my guess where the problems come, but OK. Let's see what happens down the road.

**Comment by tfarago** [comment]
The obvious problem is fixed here, inconsistencies in reconstruction will be dealt with elsewhere.

**Pull request merged**
